# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5060c8869de711f00f12c7d4633780c6ca86ee94b34fb102ced47f6cccd6267b24179ac1d3d3efec733a7133ebf4c478d2e43244cdc396a2d99162c569bcd2c

test:
  secret_key_base: d268de4aca886ac85fd35bd1dc26d0e333d3ed711622489a0a9c48dea3a9e9488c5e597800cb1b0ca78dd1f814c42fdde3b2c84fd6264b9d0da359e9e3724340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
